### ISSUE TITLE
Release 1.0.6 on Rubygems

### ISSUE THREAD

**Issue by kwent** [PrintNode/PrintNode-Ruby#11]
Hi,

1.0.5 has been released in 2015 and this library had many improvements done since. 

Can we cut a 1.0.6 release and upload on Rubygems ?

Thanks

**Comment by jmmastey** [comment]
@PrintNodeLtd @printnode-jake could you take a look at this? It would be a trivial change.

**Comment by PrintNodeJames** [comment]
We've done a rubygems release 1.0.7. Please let us know if there are any problems.

--- original message ---
On June 14, 2019, 2:59 PM UTC notifications@github.com wrote:


@PrintNodeLtd @printnode-jake could you take a look at this? It would be a trivial change.

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---

**Comment by jmmastey** [comment]
Everything is perfect, thanks!

**Comment by kwent** [comment]
Good on my side as well. Thank you!
